### ISSUE TITLE
What is the difference between TransitiveMetadataReferences and MetadataReferences?

### ISSUE THREAD

**Issue by jeuxjeux20** [GuOrg/Gu.Roslyn.Asserts#112]
Hello,

I've been a bit stuck for this one, which should and i choose and what assemblies should i put for them?

**Comment by JohanLarsson** [comment]
Sounds like we have some missing/bad docs

The idea behind `TransitiveMetadataReferences` is that it walks the type you pass in and figures out all recursive `MetadataReference`s.

Say we are writing an analyzer for `AspNetCore` code, then the idea is that we should be able to write:

```cs
[assembly: TransitiveMetadataReferences(
    typeof(Microsoft.EntityFrameworkCore.DbContext),
    typeof(Microsoft.AspNetCore.Mvc.Controller))]
```

And that `TransitiveMetadataReferences` should figure out all 1000? `MetaDataReference`s to add.

So then when you write:

```cs
        [Test]
        public static void SomeTest()
        {
            var code = @"
namespace AspBox
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;

    [ApiController]
    public class OrdersController : Controller
    {
        [HttpGet(""api/orders/{id}"")]
        public IActionResult Get(int id)
        {
            return this.Ok(id);
        }
    }
}";
            RoslynAssert.Valid(Analyzer, code);
        }
```

`RoslynAssert` will have all `MetaDataReference`s for the test code to compile.

Don't know if the above explanation makes any sense. The API is not great around here, I could not figure out a nicer way than to use an attribute.

**Comment by JohanLarsson** [comment]
I don't know if the above answers your question, maybe we should start with what problem you are solving.

**Comment by JohanLarsson** [comment]
`MetaDataReferences` is a helper class that for example has a `FromAttributes()` method that gets what was passed in via `[assembly: MetadataReference(...)]`

You can for example use it like this:

```cs
var compilation = CSharpCompilation.Create(
    "TestProject",
    new[] { syntaxTree },
    MetadataReferences.FromAttributes());
```
