### ISSUE TITLE
Cleanup overloads

### ISSUE THREAD

**Issue by JohanLarsson** [GuOrg/Gu.Roslyn.Asserts#113]
It is a terrible mess now.

Should be:

```cs
public static void CodeFix(DiagnosticAnalyzer analyzer, CodeFixProvider fix, string before, string after, <optional parameters>)
```

Still needs overloads for `IReadOnlyList<string> before`

Same for Valid, Diagnostics etc. Marking things `[Obsolete]`to start with but not sure there is a way to do this without nasty breaking changes.

**Comment by JohanLarsson** [comment]
@mikkelbu we are cleaning up the terrible overload mess that happened. There will be some breaking changes but we will ship an analyzer with the nuget that fixes them.

**Comment by mikkelbu** [comment]
@JohanLarsson No worries. Only good to clean up the code :)

**Comment by JohanLarsson** [comment]
Think we are closer now. Hopefully the analyzer fixes places where we did breaking changes.
