### ISSUE TITLE
Solution cannot be found based on project

### ISSUE THREAD

**Issue by GeertvanHorrik** [GuOrg/Gu.Roslyn.Asserts#138]
Probably this code:

https://github.com/GuOrg/Gu.Roslyn.Asserts/blob/master/Gu.Roslyn.Asserts/SolutionFile.cs#L22

![image](https://user-images.githubusercontent.com/1246444/61936572-50a8cc80-af8d-11e9-8058-d7f802ca0c55.png)

**Comment by JohanLarsson** [comment]
Thanks for reporting, better error message and bugfix needed there. Please write issues when messages are bad if you have time. Goal is that the lib should produce actually helpful messages but we have some work to do there.

**Comment by JohanLarsson** [comment]
Will be a while before I can release, hopefully tomorrow.
