### ISSUE TITLE
Support testing DiagnosticSuppressor

### ISSUE THREAD

**Issue by JohanLarsson** [GuOrg/Gu.Roslyn.Asserts#165]

**Comment by manfred-brands** [comment]
I have some code used in nunit.analyzers that could be used as a basis: [DiagnosticsSuppressorAnalyzer](https://github.com/nunit/nunit.analyzers/blob/master/src/nunit.analyzers.tests/DiagnosticSuppressors/DiagnosticsSuppressorAnalyzer.cs)

It can be used in a similar way to `RoslynAssert.Diagnostics`:
```csharp
await DiagnosticsSuppressorAnalyzer.EnsureSuppressed(suppressor,
    NonNullableFieldOrPropertyIsUninitializedSuppressor.NullableFieldOrPropertyInitializedInSetUp, testCode)
    .ConfigureAwait(false);
```

It does a two part compilation. 
1. A normal one, ensure that there are errors matching the supplied `SuppressionDescriptor`
2. One with the `DiagnosticsSuppressor` enabled, now verifying that the previous error is now suppressed.

As the remaining tests in nunit.analyzers use Gu.Roslyn.Assert moving it would be a good thing.
Maybe as an `RoslynAssert.EnsureSuppressed` or similar.

The main difference would be to replace the `TestHelpers.CreateCompilation` with the equivalent in your project.

**Comment by manfred-brands** [comment]
I'm now using my code in a 2nd Analyzer, would you consider a PR to add this to your project?

**Comment by JohanLarsson** [comment]
Yes!
Sounds like a nice fit.

**Comment by manfred-brands** [comment]
Will try to get this done this weekend.

**Comment by JohanLarsson** [comment]
Wonder what a good name is?

Maybe
```cs
RoslynAssert.NoDiagnostic(Suppressor, code);
```
