### ISSUE TITLE
Set language version of RoslynAssert calls

### ISSUE THREAD

**Issue by manfred-brands** [GuOrg/Gu.Roslyn.Asserts#231]
Hi, I tried upgrading to Gu.Roslyn.Assert version 4.0 in the nunit.analyzers project.
It however causes test to fail due to a roslyn C#10 bug (https://github.com/nunit/nunit/issues/3993).

I see that you have a LanguageVersion option to CodeFactory.CreateSolution but this is not exposed on `RoslynAssert.CodeFix`
Is there a way to (globally) force C#9 language version?

**Comment by JohanLarsson** [comment]
> Is there a way to (globally) force C#9 language version?

Not that I remember.

**Comment by JohanLarsson** [comment]
> It however causes test to fail due to a roslyn C#10 bug

We can perhaps add a suppressor for the bug as we have an analyzer.

**Comment by manfred-brands** [comment]
Would you accept a PR allowing to pass in Language version to these methods?

**Comment by JohanLarsson** [comment]
Not sure, had a huge number of overloads, been refactoring away from that mess.

Plan is to add a settings object that can be passed in.

**Comment by JohanLarsson** [comment]
Started looking into this, it looks like it will be a nasty hard breaking change due to current overloads with default parameter values.

**Comment by manfred-brands** [comment]
I noticed that too, the only place I saw a `LanguageVersion` was `CreateSolution` which is called indirectly from `RoslynAssert.Valid`

A static `RoslynAssert.LanguageVersion` version would work, but is nasty, when tests in a solution set different versions and run in parallel.
An other alternative would to load a `RoslynAssert.Settings` file.

**Comment by JohanLarsson** [comment]
Everything about this is unfortunate. Maybe the best we can do is to clean things up with a breaking change, not much fun for users of the package.

**Comment by manfred-brands** [comment]
Or wait for Roslyn to release a new version of the compiler with the bug fix, making this unnecessary (for now)

**Comment by JohanLarsson** [comment]
https://www.nuget.org/packages/Gu.Roslyn.Asserts/4.0.1

All I can say is sorry, broke everything.
