### ISSUE TITLE
Verify doesn't allow diagnostics with the same id

### ISSUE THREAD

**Issue by manfred-brands** [GuOrg/Gu.Roslyn.Asserts#253]
This is the same as #99 which was then solved by the writer to make all id's unique.

I ran into this again with another Analyzer.
Looking at the Roslyn analyzer they also use multiple DiagnosticsDescriptors with the same Id, just with different message/title.
See:

* [IdentifiersShouldNotMatchKeywords](https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/IdentifiersShouldNotMatchKeywords.cs)
- [DefineAccessorsForAttributeArguments](https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DefineAccessorsForAttributeArguments.cs)

There are several others.

So I think the Unique test in RoslynAssert.cs `VerifyAnalyzerSupportsDiagnostic` should be removed.

Currently `ExpectedDiagnostic` only works on the RuleId, maybe it should work on `DiagnosticDescriptor` instead which then needs to be one listed in the `SupportedDiagnostics`.

**Comment by JohanLarsson** [comment]
This should also have been a separate pull request.

**Comment by manfred-brands** [comment]
I offered to split it off. Didn't expect it to be accepted straight away.

**Comment by JohanLarsson** [comment]
Ok, no worries.
Just wanted to put my foot down in case it was designed as hidden cargo in the PR :D
