### ISSUE TITLE
ExpectedDiagnostic.Create throws ArgumentNullException

### ISSUE THREAD

**Issue by dnperfors** [GuOrg/Gu.Roslyn.Asserts#66]
When using the ExpectedDiagnostic.Create method an ArgumentNullException is thrown by FileLinePositionSpan, because the constructor of FileLinePositionSpan doesn't allow a `null` path: https://github.com/GuOrg/Gu.Roslyn.Asserts/blob/master/Gu.Roslyn.Asserts/ExpectedDiagnostic.cs#L119

Work around would be to use CreateFromCodeWithErrorsIndicated, since that one generates a filename.

**Comment by JohanLarsson** [comment]
That was a dumb bug, thanks for reporting!

**Comment by JohanLarsson** [comment]
You can use the constructor `public ExpectedDiagnostic(string id, string message, FileLinePositionSpan span)` for creating but not sure how it works with the asserts. I forgot about this API, never used it.

**Comment by JohanLarsson** [comment]
Note that if you have error position indicated you can just do:
```cs
[Test]
public void CheckMessageAlso()
{
    var code = @"
namespace RoslynSandbox
{
    class Foo
    {
        private readonly int ↓_value;
    }
}";
    var expectedDiagnostic = ExpectedDiagnostic.Create("SA1309", "Field '_value1' must not begin with an underscore");
    AnalyzerAssert.Diagnostics<FieldNameMustNotBeginWithUnderscore>(expectedDiagnostic, code);
}
```

I updated the docs with this.

**Comment by dnperfors** [comment]
Thanks for the fix. In general I find using the error position indicator not that intuitive, because of the arrow character (or I should learn how to quickly type that character without copy past ;))

**Comment by JohanLarsson** [comment]
If you have alpha numeric keyboard you type it with `alt + 25`. Not so fun on laptop.
The roslyn guys use `[|...|]` to indicate error position. 
Reopened https://github.com/GuOrg/Gu.Roslyn.Asserts/issues/6

Should be pretty easy to add support but API will not be pretty I think.

**Comment by JohanLarsson** [comment]
Reason for picking `↓` to indicate error position indicator was that it will not show up much in the tested code.
